export const nbateams = [
    { name: 'Atlanta Hawks', id: '1610612737' },
    { name: 'Boston Celtics', id: '1610612738' },
    { name: 'Brooklyn Nets', id: '1610612751' },
    { name: 'Charlotte Hornets', id: '1610612766' },
    { name: 'Chicago Bulls', id: '1610612741' },
    { name: 'Cleveland Cavaliers', id: '1610612739' },
    { name: 'Dallas Mavericks', id: '1610612742' },
    { name: 'Denver Nuggets', id: '1610612743' },
    { name: 'Detroit Pistons', id: '1610612765' },
    { name: 'Golden State Warriors', id: '1610612744' },
    { name: 'Houston Rockets', id: '1610612745' },
    { name: 'Indiana Pacers', id: '1610612754' },
    { name: 'Los Angeles Clippers', id: '1610612746' },
    { name: 'Los Angeles Lakers', id: '1610612747' },
    { name: 'Memphis Grizzlies', id: '1610612763' },
    { name: 'Miami Heat', id: '1610612748' },
    { name: 'Milwaukee Bucks', id: '1610612749' },
    { name: 'Minnesota Timberwolves', id: '1610612750' },
    { name: 'New Orleans Pelicans', id: '1610612740' },
    { name: 'New York Knicks', id: '1610612752' },
    { name: 'Oklahoma City Thunder', id: '1610612760' },
    { name: 'Orlando Magic', id: '1610612753' },
    { name: 'Philadelphia 76ers', id: '1610612755' },
    { name: 'Phoenix Suns', id: '1610612756' },
    { name: 'Portland Trail Blazers', id: '1610612757' },
    { name: 'Sacramento Kings', id: '1610612758' },
    { name: 'San Antonio Spurs', id: '1610612759' },
    { name: 'Toronto Raptors', id: '1610612761' },
    { name: 'Utah Jazz', id: '1610612762' },
    { name: 'Washington Wizards', id: '1610612764' }
];

export const nflteams = [
    { name: 'Arizona Cardinals', id: 'ARI' },
    { name: 'Atlanta Falcons', id: 'ATL' },
    { name: 'Baltimore Ravens', id: 'BAL' },
    { name: 'Buffalo Bills', id: 'BUF' },
    { name: 'Carolina Panthers', id: 'CAR' },
    { name: 'Chicago Bears', id: 'CHI' },
    { name: 'Cincinnati Bengals', id: 'CIN' },
    { name: 'Cleveland Browns', id: 'CLE' },
    { name: 'Dallas Cowboys', id: 'DAL' },
    { name: 'Denver Broncos', id: 'DEN' },
    { name: 'Detroit Lions', id: 'DET' },
    { name: 'Green Bay Packers', id: 'GB' },
    { name: 'Houston Texans', id: 'HOU' },
    { name: 'Indianapolis Colts', id: 'IND' },
    { name: 'Jacksonville Jaguars', id: 'JAX' },
    { name: 'Kansas City Chiefs', id: 'KC' },
    { name: 'Las Vegas Raiders', id: 'LV' },
    { name: 'Los Angeles Chargers', id: 'LAC' },
    { name: 'Los Angeles Rams', id: 'LAR' },
    { name: 'Miami Dolphins', id: 'MIA' },
    { name: 'Minnesota Vikings', id: 'MIN' },
    { name: 'New England Patriots', id: 'NE' },
    { name: 'New Orleans Saints', id: 'NO' },
    { name: 'New York Giants', id: 'NYG' },
    { name: 'New York Jets', id: 'NYJ' },
    { name: 'Philadelphia Eagles', id: 'PHI' },
    { name: 'Pittsburgh Steelers', id: 'PIT' },
    { name: 'San Francisco 49ers', id: 'SF' },
    { name: 'Seattle Seahawks', id: 'SEA' },
    { name: 'Tampa Bay Buccaneers', id: 'TB' },
    { name: 'Tennessee Titans', id: 'TEN' },
    { name: 'Washington Commanders', id: 'WSH' }
];

export const eplteams = [
    { name: 'Arsenal', id: '2001' },
    { name: 'Aston Villa', id: '2002' },
    { name: 'Bournemouth', id: '2003' },
    { name: 'Brentford', id: '2004' },
    { name: 'Brighton & Hove Albion', id: '2005' },
    { name: 'Chelsea', id: '2006' },
    { name: 'Crystal Palace', id: '2007' },
    { name: 'Everton', id: '2008' },
    { name: 'Fulham', id: '2009' },
    { name: 'Ipswich Town', id: '2010' },
    { name: 'Leicester City', id: '2011' },
    { name: 'Liverpool', id: '2012' },
    { name: 'Manchester City', id: '2013' },
    { name: 'Manchester United', id: '2014' },
    { name: 'Newcastle United', id: '2015' },
    { name: 'Nottingham Forest', id: '2016' },
    { name: 'Southampton', id: '2017' },
    { name: 'Tottenham Hotspur', id: '2018' },
    { name: 'West Ham United', id: '2019' },
    { name: 'Wolverhampton Wanderers', id: '2020' }
];